import { formatCurrency, MVP_PRICING } from './pricing.js';

export const SHOP_CATEGORIES = Object.freeze([
  { id: 'all', number: '01', label: 'Shop everything', shortLabel: 'The full TOMA table', tone: '#3c2518' },
  { id: 'everyday', number: '02', label: 'Everyday cups', shortLabel: 'Reliable daily energy', tone: '#7b4326' },
  { id: 'turkish', number: '03', label: 'Turkish coffee', shortLabel: 'Fine-ground tradition', tone: '#a46e3e' },
  { id: 'instant', number: '04', label: 'Instant & easy', shortLabel: 'Good coffee, faster', tone: '#d2a668' },
  { id: 'bundles', number: '05', label: 'Bundles', shortLabel: 'More than one good cup', tone: '#3e4b38' },
]);

export const SHOP_HERO_SLIDES = Object.freeze([
  { id: 'turbo', eyebrow: 'TOMA COFFEE / NEW DROP 01', titleLine: 'Turkish coffee', titleEmphasis: 'with a little more drive.', copy: 'Freshly ground Egyptian Turkish coffee blended with Korean red ginseng. A stronger daily ritual, made with the care of twelve years in coffee.', ctaLabel: 'Shop Turbo Mode', ctaTarget: '#collection', secondaryLabel: 'See the shelf', secondaryTarget: '#collection', image: '/assets/toma-turbo-editorial.png', label: 'TURBO MODE', note: 'FRESH / HOT / SELECTED', proof: ['50g pack', 'Freshly ground', 'Made in Egypt'] },
  { id: 'blend', eyebrow: 'TOMA BLEND LAB / YOUR DIRECTION', titleLine: 'Make the next cup', titleEmphasis: 'a signature.', copy: 'Start with a moment, shape the character, and leave with a blend that has a reason behind it.', ctaLabel: 'Open Blend Lab', ctaTarget: '/blend-lab', secondaryLabel: 'Browse ready-made', secondaryTarget: '#collection', image: '/assets/toma-blend-lab-editorial.png', label: 'BLEND LAB', note: 'GUIDED / BALANCED / YOURS', proof: ['6 moments', '3 useful controls', 'Your recipe'] },
  { id: 'bundle', eyebrow: 'TOMA / COLLECTION 01', titleLine: 'More than one', titleEmphasis: 'good cup.', copy: 'Keep your everyday favourite close and make room for the next direction. TOMA bundles are selected around real coffee rhythms.', ctaLabel: 'Explore bundles', ctaTarget: '#bundles', secondaryLabel: 'Shop everything', secondaryTarget: '#collection', image: '/assets/toma-bundle-editorial.png', label: 'COLLECTION 01', note: 'SELECTED / TOGETHER / READY', proof: ['5 bundles', 'Save by direction', 'Share the ritual'] },
  { id: 'instant', eyebrow: 'TOMA / THE QUICK CUP', titleLine: 'Instant can still', titleEmphasis: 'have a point of view.', copy: 'A bright, clean shortcut for the mornings that move quickly — with a cup worth coming back to.', ctaLabel: 'Shop instant coffee', ctaTarget: '#collection', secondaryLabel: 'See the offers', secondaryTarget: '#offers', image: '/assets/toma-instant-editorial.png', label: 'GOLD INSTANT', note: 'QUICK / BRIGHT / CONSIDERED', proof: ['100g jar', 'Ready in seconds', 'Clean finish'] },
  { id: 'ritual', eyebrow: 'TOMA / TURKISH TABLE', titleLine: 'Leave room for', titleEmphasis: 'a slower cup.', copy: 'Cardamom, coffee, and a little more ceremony. Explore the warmer side of the TOMA shelf.', ctaLabel: 'Shop Turkish coffee', ctaTarget: '#collection', secondaryLabel: 'Ask TOMA', secondaryTarget: '#contact', image: '/assets/toma-hero-v2.png', label: 'TURKISH TABLE', note: 'WARM / AROMATIC / SLOW', proof: ['100g pack', 'Fine-ground', 'Measured spice'] },
]);

export const SHOP_PRODUCTS = Object.freeze([
  { id: 'turbo-mode-50g', type: 'product', name: 'TOMA Turbo Mode', category: 'everyday', categoryLabel: 'Everyday cup', badge: 'New drop', subtitle: 'Egyptian Turkish coffee / Korean red ginseng', description: 'Freshly ground with a little more drive for the first cup that needs to show up.', notes: 'Bold · familiar · warming', packSizeGrams: 50, sizeLabel: '50g pack', unitPrice: 250, currency: MVP_PRICING.currency, priceLabel: formatCurrency(250), image: '/assets/toma-turbo-editorial.png', tone: '#6e3b21' },
  { id: 'morning-classic-100g', type: 'product', name: 'Morning Classic', category: 'everyday', categoryLabel: 'Everyday cup', badge: 'Daily favourite', subtitle: 'Egyptian coffee / medium roast', description: 'The clear, dependable pack for the mornings that already know their rhythm.', notes: 'Smooth · steady · familiar', packSizeGrams: 100, sizeLabel: '100g pack', unitPrice: 350, currency: MVP_PRICING.currency, priceLabel: formatCurrency(350), image: '/assets/toma-blend-lab-editorial.png', tone: '#7d5739' },
  { id: 'cacao-night-100g', type: 'product', name: 'Cacao Night', category: 'everyday', categoryLabel: 'Everyday cup', badge: 'Limited blend', subtitle: 'Turkish coffee / roasted cacao', description: 'A darker, softer direction for late cups and slower conversations.', notes: 'Cacao · deep · soft', packSizeGrams: 100, sizeLabel: '100g pack', unitPrice: 450, currency: MVP_PRICING.currency, priceLabel: formatCurrency(450), image: '/assets/toma-turbo-editorial.png', tone: '#4e2a1b' },
  { id: 'house-medium-100g', type: 'product', name: 'House Medium', category: 'turkish', categoryLabel: 'Turkish coffee', badge: 'House standard', subtitle: 'Balanced Turkish coffee / medium roast', description: 'A clear, smooth centre for the days you want coffee to feel exactly right.', notes: 'Balanced · round · clean', packSizeGrams: 100, sizeLabel: '100g pack', unitPrice: 400, currency: MVP_PRICING.currency, priceLabel: formatCurrency(400), image: '/assets/toma-bundle-editorial.png', tone: '#9b7044' },
  { id: 'cardamom-ritual-100g', type: 'product', name: 'Cardamom Ritual', category: 'turkish', categoryLabel: 'Turkish coffee', badge: 'Warm note', subtitle: 'Medium Turkish coffee / measured cardamom', description: 'The TOMA starting point with a warm aromatic finish and a little more ceremony.', notes: 'Warm · aromatic · soft', packSizeGrams: 100, sizeLabel: '100g pack', unitPrice: 450, currency: MVP_PRICING.currency, priceLabel: formatCurrency(450), image: '/assets/toma-hero-v2.png', tone: '#b77b43' },
  { id: 'rose-cinnamon-100g', type: 'product', name: 'Rose Cinnamon', category: 'turkish', categoryLabel: 'Turkish coffee', badge: 'Soft spice', subtitle: 'Fine Turkish coffee / rose and cinnamon', description: 'A floral, gently spiced cup for the tables that stay a little longer.', notes: 'Floral · spiced · soft', packSizeGrams: 100, sizeLabel: '100g pack', unitPrice: 500, currency: MVP_PRICING.currency, priceLabel: formatCurrency(500), image: '/assets/toma-blend-lab-editorial.png', tone: '#986b55' },
  { id: 'quiet-decaf-100g', type: 'product', name: 'Quiet Decaf', category: 'turkish', categoryLabel: 'Turkish coffee', badge: 'Low-key cup', subtitle: 'Decaffeinated Turkish coffee / medium roast', description: 'The ritual stays; the late-night intensity does not.', notes: 'Gentle · rounded · calm', packSizeGrams: 100, sizeLabel: '100g pack', unitPrice: 450, currency: MVP_PRICING.currency, priceLabel: formatCurrency(450), image: '/assets/toma-bundle-editorial.png', tone: '#c18b55' },
  { id: 'gold-instant-100g', type: 'product', name: 'Gold Instant', category: 'instant', categoryLabel: 'Instant & easy', badge: 'New format', subtitle: 'Premium instant coffee / bright finish', description: 'A fast cup with enough character to keep the shortcut honest.', notes: 'Bright · easy · clean', packSizeGrams: 100, sizeLabel: '100g jar', unitPrice: 350, currency: MVP_PRICING.currency, priceLabel: formatCurrency(350), image: '/assets/toma-instant-editorial.png', tone: '#d6af64' },
  { id: 'velvet-instant-100g', type: 'product', name: 'Velvet Instant', category: 'instant', categoryLabel: 'Instant & easy', badge: 'Smooth shortcut', subtitle: 'Instant coffee / cocoa finish', description: 'A fuller instant cup with a soft finish for desk-side refills.', notes: 'Velvety · quick · mellow', packSizeGrams: 100, sizeLabel: '100g jar', unitPrice: 400, currency: MVP_PRICING.currency, priceLabel: formatCurrency(400), image: '/assets/toma-instant-editorial.png', tone: '#c2975e' },
  { id: 'orange-mocha-100g', type: 'product', name: 'Orange Mocha', category: 'everyday', categoryLabel: 'Everyday cup', badge: 'New direction', subtitle: 'Turkish coffee / orange and cacao', description: 'A bright aromatic edge over a chocolate base for a more playful daily cup.', notes: 'Citrus · cacao · warm', packSizeGrams: 100, sizeLabel: '100g pack', unitPrice: 500, currency: MVP_PRICING.currency, priceLabel: formatCurrency(500), image: '/assets/toma-hero-v2.png', tone: '#a46638' },
]);

export const SHOP_BUNDLES = Object.freeze([
  { id: 'bundle-morning-mode', type: 'product', name: 'Morning Mode', badge: 'Best place to start', subtitle: 'Turbo Mode + Gold Instant', description: 'One bold first cup and one easy backup for the mornings that move quickly.', itemsLabel: '2 packs · ready for the week', unitPrice: 550, currency: MVP_PRICING.currency, priceLabel: formatCurrency(550), compareLabel: `${formatCurrency(600)} separately`, image: '/assets/toma-bundle-editorial.png', tone: '#7b4326' },
  { id: 'bundle-turkish-table', type: 'product', name: 'The Turkish Table', badge: 'Share the ritual', subtitle: 'House Medium + Cardamom Ritual', description: 'Two clear directions for a table, a long afternoon, or choosing together.', itemsLabel: '2 × 100g packs', unitPrice: 750, currency: MVP_PRICING.currency, priceLabel: formatCurrency(750), compareLabel: `${formatCurrency(850)} separately`, image: '/assets/toma-hero-v2.png', tone: '#3e4b38' },
  { id: 'bundle-discovery-three', type: 'product', name: 'Discovery Three', badge: 'Try the range', subtitle: 'Turbo Mode + Cacao Night + Quiet Decaf', description: 'Three different moments, selected to make your next favourite easier to find.', itemsLabel: '3 packs · guided selection', unitPrice: 1000, currency: MVP_PRICING.currency, priceLabel: formatCurrency(1000), compareLabel: `${formatCurrency(1150)} separately`, image: '/assets/toma-bundle-editorial.png', tone: '#a46e3e' },
  { id: 'bundle-instant-backup', type: 'product', name: 'Instant Backup', badge: 'Desk drawer essential', subtitle: 'Gold Instant + Velvet Instant', description: 'Two quick cups for the mornings that do not leave room for a long brew.', itemsLabel: '2 × 100g jars', unitPrice: 680, currency: MVP_PRICING.currency, priceLabel: formatCurrency(680), compareLabel: `${formatCurrency(750)} separately`, image: '/assets/toma-instant-editorial.png', tone: '#b99558' },
  { id: 'bundle-slow-evening', type: 'product', name: 'Slow Evening', badge: 'For the later cup', subtitle: 'Cardamom Ritual + Quiet Decaf', description: 'A warmer spice-led cup paired with a softer decaf ritual for after hours.', itemsLabel: '2 × 100g packs', unitPrice: 850, currency: MVP_PRICING.currency, priceLabel: formatCurrency(850), compareLabel: `${formatCurrency(900)} separately`, image: '/assets/toma-hero-v2.png', tone: '#5c493b' },
  { id: 'bundle-full-shelf', type: 'product', name: 'The Full Shelf', badge: 'Most TOMA directions', subtitle: 'Six selected packs and jars', description: 'A generous starting point across everyday, Turkish, and instant coffee directions.', itemsLabel: '6 products · curated shelf', unitPrice: 2250, currency: MVP_PRICING.currency, priceLabel: formatCurrency(2250), compareLabel: `${formatCurrency(2500)} separately`, image: '/assets/toma-bundle-editorial.png', tone: '#43503a' },
]);

export const SHOP_OFFERS = Object.freeze([
  { label: 'Bundle value', detail: 'Save up to 10% when directions travel together.' },
  { label: 'First shelf', detail: 'Start with a guided three-pack and find your next favourite.' },
  { label: 'Blend Lab', detail: 'Build a custom recipe when the ready-made shelf is not enough.' },
]);

export const SHOP_REVIEWS = Object.freeze([
  { quote: 'Turbo Mode became the cup I make when I have a lot to do but still want the ritual.', name: 'Mariam', detail: 'Morning routine / MVP sample' },
  { quote: 'The blend guide made the choice feel simple. I finally know why I like a medium roast.', name: 'Omar', detail: 'Blend Lab customer / MVP sample' },
  { quote: 'The cardamom is present without taking over. It tastes considered, not flavoured.', name: 'Salma', detail: 'Turkish coffee drinker / MVP sample' },
]);

export const SHOP_PROOF = Object.freeze([
  { number: '01', title: 'Freshly ground', copy: 'The cup starts with coffee prepared for the way you actually brew it.' },
  { number: '02', title: 'Made in Egypt', copy: 'Local craft, selected ingredients, and a standard TOMA can repeat.' },
  { number: '03', title: 'Clear by design', copy: 'Every product tells you its format, character, pack, and next best use.' },
  { number: '04', title: 'Guided when you need it', copy: 'When the shelf is not enough, the Blend Lab helps you make your own direction.' },
]);
