import { BODY_OPTIONS, GOALS, ROAST_OPTIONS } from '../../lib/blend-rules.js';
import { TomaIcon } from '../TomaIcon.jsx';
import { faCircleDot } from '@fortawesome/free-solid-svg-icons';

function PreferenceSelect({ id, label, value, options, onChange }) {
  return <label className="profile-preference-field" htmlFor={id}><span>{label}</span><select id={id} value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>;
}

export function PreferencePanel({ preferences, onChange }) {
  return <section id="settings" className="profile-panel preference-panel" aria-labelledby="preferences-title"><div className="profile-panel-heading"><div><p className="eyebrow">The way you choose</p><h2 id="preferences-title">Your preferences.</h2></div><span className="profile-live-mark">Saved on this device</span></div><p className="profile-panel-lede">A starting point for the next cup. Change it whenever your taste moves.</p><div className="profile-preference-grid"><PreferenceSelect id="preference-moment" label="Coffee moment" value={preferences.momentId} options={GOALS.map((goal) => ({ value: goal.id, label: goal.label }))} onChange={(value) => onChange({ momentId: value })} /><PreferenceSelect id="preference-body" label="Body" value={preferences.body} options={BODY_OPTIONS.map((option) => ({ value: option.id, label: option.label }))} onChange={(value) => onChange({ body: value })} /><PreferenceSelect id="preference-roast" label="Roast" value={preferences.roast} options={ROAST_OPTIONS.map((option) => ({ value: option.id, label: option.label }))} onChange={(value) => onChange({ roast: value })} /><PreferenceSelect id="preference-addition" label="Aromatic addition" value={String(preferences.additionPercent)} options={[{ value: '0', label: 'Plain coffee' }, { value: '2', label: 'Cardamom · 2%' }, { value: '3', label: 'Cardamom · 3%' }, { value: '5', label: 'Cardamom · 5%' }]} onChange={(value) => onChange({ additionPercent: Number(value) })} /></div><div className="profile-format-lock"><TomaIcon icon={faCircleDot} /><p><strong>Turkish coffee</strong><br />Fine grind / currently available format</p><span className="profile-lock-label">Configured</span></div></section>;
}
